### ISSUE TITLE
[standup] Q1 P0

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/oep#243]
This issue will consist of team plans w.r.t p0 e2e test cases after the introduction of TCID aka TestCaseID. A new comment can be started off by each team member & updated marking the progress of their tasks.

**Comment by AmitKumarDas** [comment]
## Team Member AmitKumarDas
- P0 e2e testcases implementation
  - None _mention the PR links here_
- P0 e2e readme implementation
  - None _mention the PR links here_
- P0 e2e stage/job implementation
  - None _mention the PR links here_
- P0 e2e gitlab-ci.yml changes
  - None _mention in this issue comment in a `yaml` format_

Amit is ensuring completion of P0 e2e test cases & their documentation.

**Comment by uditgaurav** [comment]
## Team Member Udit Gaurav
- P0 e2e testcases implementation
  - [x] https://github.com/mayadata-io/oep/pull/233
  - [x] https://github.com/mayadata-io/oep/pull/232
  - [x] https://github.com/mayadata-io/oep/pull/228
- P0 e2e readme implementation
   - [x] openebs-self-installation-check - https://bit.ly/2PFEfGz
   - [x] openebs-data-plane-test - https://bit.ly/2TjKdit
   - [x] Openebs control plane test- https://bit.ly/2PIijKJ
- P0 e2e stage/job implementation
  - [x] None
- P0 e2e gitlab-ci.yml changes
  ```yaml  
  None
  ```

Amit is ensuring completion of P0 e2e test cases & their documentation.

**Comment by amitbhatt818** [comment]
## Team Member Amit Bhatt
- P0 e2e testcases implementation
  - [x] https://github.com/mayadata-io/oep/pull/208  (openebs-installation-check)
  - [x] https://github.com/mayadata-io/oep/pull/230 (openebs-upgrade-jiva-check)
- P0 e2e readme implementation
   - [x]  openebs-installation-check
   - [ ]  Openebs-upgrade-jiva-check
- P0 e2e stage/job implementation
  - [x] tcid-iuoi02-openebs-install
  - [x] tcid-iuod27-openebs-upgrade-jiva

- P0 e2e gitlab-ci.yml changes

- [x] openebs-install-test
```
## openebs install check
tcid-iuoi02-openebs-install-check:
  image: harshshekhar15/gitlab-job:v1
  stage: OPENEBS-INSTALL-CHECK
  dependencies:
    - cluster-setup-check
  script: 
    - chmod 755 ./stages/9-openebs-install-check/openebs-install-check
    - ./stages/9-openebs-install-check/openebs-install-check
```
   - [x] openebs-upgrade-jiva-test

```
## Volume upgrade Jiva Check
tcid-iuod27-volume-upgrade-jiva-check:
  image: harshshekhar15/gitlab-job:v1
  stage: OPENEBS-UPGRADE-CHECK
  dependencies:
    - cluster-setup-check
  script:
    - chmod 755 ./stages/10-openebs-upgrade-check/volume-upgrade-jiva-check
    - ./stages/10-openebs-upgrade-check/volume-upgrade-jiva-check

```

**Comment by shiveshabhishek** [comment]
## Team Member ShiveshAbhishek
- P0 e2e testcases implementation
  - [x] #214 (openebs-upgrade-check)
- P0 e2e readme implementation
  - [x] [Pool Upgrade Check](https://github.com/mayadata-io/oep-e2e-gcp/blob/master/stages/10-openebs-upgrade-check/pool-upgrade-check.md)
  - [x] [Volume Upgrade Check](https://github.com/mayadata-io/oep-e2e-gcp/blob/master/stages/10-openebs-upgrade-check/volume-upgrade-check.md)

- P0 e2e stage/job implementation
  - [x] [tcid-iuod01] openebs-upgrade-check
- P0 e2e gitlab-ci.yml changes

 ```  
## Pool Upgrade Check
tcid-iuod08-pool-upgrade-check:
  image: harshshekhar15/gitlab-job:v1
  stage: OPENEBS-UPGRADE-CHECK
  dependencies:
    - cluster-setup-check
  script:
    - chmod 755 ./stages/10-openebs-upgrade-check/pool-upgrade-check
    - ./stages/10-openebs-upgrade-check/pool-upgrade-check

## Volume Upgrade Check
tcid-iuod12-volume-upgrade-check:
  image: harshshekhar15/gitlab-job:v1
  stage: OPENEBS-UPGRADE-CHECK
  dependencies:
    - cluster-setup-check
  script:
    - chmod 755 ./stages/10-openebs-upgrade-check/volume-upgrade-check
    - ./stages/10-openebs-upgrade-check/volume-upgrade-check  
  ```

Shivesh is ensuring the refactoring of the above README and completion of other test cases
